---
title: "R Notebook"
output: html_notebook
---


```{r}
plot(cars)
```
```{r}
install.packages("mlbench")
library(mlbench)
```
```{r}
data(Zoo)
head(Zoo)
summary(Zoo)
```
```{r}
for(i in c(1:12,14:16))Zoo[[i]]<-as.factor(Zoo[[i]])
summary(Zoo)
```
```{r}
install.packages("rpart")
library(rpart)
```
```{r}
tree_default<- rpart(type~.,data=Zoo)
tree_default
```
```{r}
install.packages("rpart.plot")
library(rpart.plot)
```
```{r}
rpart.plot(tree_default,extra=1,under=TRUE,varlen=0,faclen=0)
#extra =2 printsfor each leaf node the no of correctly classified objects and the total no. of objects from data and the total no. of object from the training data falling into that node 
```
```{r}
tree_full<-rpart(type~.,data=Zoo,control=rpart.control(minsplit = 2,cp=0))
tree_full
```
```{r}
rpart.plot(tree_full,extra=2,under=TRUE,varlen=0,faclen=0)
```
```{r}
#metrics to assess the quality of classifier
#confusion matrix
#tp= those instance where predicted class=actual class are called true positive.
#tn= those instances where predicted class and actaul class are both negative are called true negative.
#fp=those instances where predicted class is positive but actually the instances are negative.
#fn= those instances where predicted class is negative but actually the instances are positive
```
```{r}
install.packages("rsample")
install.packages("dplyr")
install.packages("ggplot2")


```
```{r}
install.packages("caret")
```
```{r}
library(caret)
```
```{r}

library(rsample)


```
```{r}

library(dplyr)


```


